### ISSUE TITLE
Double vs. Single Quotes

### ISSUE THREAD

**Issue by smlombardi** [prettier/stylelint-prettier#20] opened 2019-05-02 18:01 UTC
**What version of `stylelint`, `prettier` and `stylelint-prettier` are you using?**
    "prettier": "1.17.0",
    "stylelint": "10.0.1",
    "stylelint-config-prettier": "^5.1.0",
    "stylelint-config-standard": "18.3.0",
    "stylelint-prettier": "1.0.6"

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.stylelintrc` files)**

#### .stylelintrc:
```
{
  "extends": [
    "stylelint-prettier/recommended"
  ],
  "rules": {
    "prettier/prettier": [
      true,
      {
        "singleQuote": true,
        "tabWidth": 2
      }
    ]
  }
}
```

#### .prettierrc
```
{
  "printWidth": 120,
  "singleQuote": true,
  "useTabs": false,
  "tabWidth": 2,
  "semi": true,
  "bracketSpacing": true
 }
```

**What source code are you linting?**
```
@import "home";
@import "payments";
@import "registration";
@import "rewards";
```

**What actually happened?**

Saving the file in VSCode formats this with double-quotes.  This is then flagged as a prettier warning.  Even if I fix them to single quotes, they are returned to double on format.

The only way to suppress the warning is to set the config to
```
    "prettier/prettier": [
      true,
      {
        "singleQuote": false,
        "tabWidth": 2
      }
    ]
```

So, I can only use double-quotes for strings.  Not the end of the world, but why?

I saw [this issue](https://github.com/prettier/stylelint-prettier/issues/9) which explains how to override prettier to allow fo double quotes — but that doesn't explain why the formatter keeps using double quotes.

**Comment by j-f1** [comment] 2019-05-03 18:29
Do you have any other formatters installed? They could be conflicting.

**Comment by BPScott** [comment] 2019-05-06 15:48
Are you able to exclude VSCode from the process? What happens in you run stylelint over the file on the command line? Does the issue continue to occur?


PS you don't need to specify `{"singleQuote": true,  "tabWidth": 2}` in your  .stylelintrc as the rule will look up your config in .prettierrc by default. You just need:

```
 "rules": {
  "prettier/prettier": true,
}
```

**Comment by smlombardi** [comment] 2019-05-07 17:19
@BPScott Even though I have done all of the above, I still get this:
<img width="849" alt="Screen Shot 2019-05-07 at 1 18 36 PM" src="https://user-images.githubusercontent.com/835148/57319510-b5f5cb80-70ca-11e9-8b03-21c160b4b93c.png">

**Comment by BPScott** [comment] 2019-05-07 19:40
That screenshot is still from within VSCode. It order to narrow down what is the issue here I'd like to take VSCode out of the equation. Can you show me the outcome of running stylelint over the file on the command line?

I've just tried to recreate this with a new empty folder and I'm unable to reproduce. I tried this with both individual `.prettierrc` and `.stylelintrc` files, and with inlining the config into package.json` and both work as expected. I'll demo the config-in-the-package.json approach as it's fewer files.

Try it yourself:

Create a new folder

In that folder place and `index.css`:

```css
@import "home";
@import 'payments';
@import 'registration';
@import 'rewards';
```

and a `package.json`:

```json
{
  "name": "test-issue",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "lint": "stylelint '*.css'",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "prettier": "^1.17.0",
    "stylelint": "^10.0.1",
    "stylelint-config-prettier": "^5.1.0",
    "stylelint-config-standard": "^18.3.0",
    "stylelint-prettier": "^1.0.7"
  }
}
```

Run `npm install`

Run `npm run lint` and see that a single linting error appears - suggesting that you change the double quotes in the `home` line to singles.


---

Let's check to see if your stylelint config is setup properly. Can you show the output when you run
`node_modules/.bin/stylelint --print-config ThePathToYourProblematicCSSFile` replacing ThePathToYourProblematicCSSFile with the filepath of your file (e.g. components/index.css). This will check to see if you've got any conflicting stylelint configs.

Also can you tell me what happens when you run prettier over that single file (`node_modules/.bin/prettier ThePathToYourProblematicCSSFile`)? What style quotes does it try and render?

**Comment by BPScott** [comment] 2019-05-08 20:28
I am an idiot and it helps if I bother to include the inlined stylelint/prettier configs in my package.json example:

My package.json example should have been the following, sorry:

```json
{
  "name": "test-issue",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "lint": "stylelint '*.css'",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "prettier": "^1.17.0",
    "stylelint": "^10.0.1",
    "stylelint-config-prettier": "^5.1.0",
    "stylelint-config-standard": "^18.3.0",
    "stylelint-prettier": "^1.0.7"
  },
  "stylelint": {
    "extends": [
      "stylelint-prettier/recommended"
    ]
  },
  "prettier": {
    "printWidth": 120,
    "singleQuote": true,
    "useTabs": false,
    "tabWidth": 2,
    "semi": true,
    "bracketSpacing": true
  }
}
```


---

That stylelint config looks reasonable (I was checking the value of the "string-quotes" property to see if it was accidentally set and conflicting with prettier).

One thing I've spotted is that you've seem to have stylelint and prettier installed globally but stylelint-prettier is installed in a project folder. I'd recommend installing specific stylelint and prettier versions into a project because you may need different versions on a per project basis. I don't think that'd affect this but who knows.

---

Are you able to host your repository somewhere I can take a look at it?

**Comment by smlombardi** [comment] 2019-05-09 13:11
Yes, now it catches the quotes on "home"
```
st016lo:~/Desktop/stylelint-test $ npm run lint

> test-issue@1.0.0 lint /Users/st016lo/Desktop/stylelint-test
> stylelint '*.css'

(node:38119) ExperimentalWarning: The fs.promises API is experimental

index.css
 1:9  ✖  Replace ""home"" with "'home'"   prettier/prettier

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! test-issue@1.0.0 lint: `stylelint '*.css'`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the test-issue@1.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/st016lo/.npm/_logs/2019-05-09T13_10_13_671Z-debug.log
```

**Comment by BPScott** [comment] 2019-05-11 12:41
Well I'm now at a loss. It clearly works but not with your project, which leads me to think it's not stylelint-prettier at fault but something in your config, though I have no idea what.

You've still not provided an example of running stylellint over your problematic file from the command line. Until I see that I'm still tempted to point the blame at VSCode doing something weird.


> Also, i DO have stylelint and prettier installed in the project

Fair enough :) It seemed strange that when you ran stylelint and prettier their paths were not in your local node_modules but at some global path but perhaps you're using Yarn PnP or something like that.

```
st016lo:~/github/ng-sample-app/client/src (story/simplify_level1) $ /Users/st016lo/.nvm/versions/node/v10.1.0/bin/stylelint --print-config styles.scss 

st016lo:~/github/ng-sample-app/client/src (story/simplify_level1) $ /Users/st016lo/.nvm/versions/node/v0.1.0/bin/prettier styles.scss                 
``

**Comment by smlombardi** [comment] 2019-05-11 15:43
I am using NVM (node version manager) which allows switching the version of Node.  Some old projects require and older version.

**Comment by BPScott** [comment] 2019-06-30 23:39
Closing as unable to reproduce

**Closed by BPScott** 2019-06-30 23:39 UTC

**Comment by ModulesUnraveled** [comment] 2021-11-01 22:44
I know this is an old thread, but I read the whole thing looking for the answer since I was having the same issue...

In my case though, it turned out my prettier config file was mis-named. I had the file`.prettier.json`... which isn't a valid config file name. Once I changed it to `.prettierrc.json` my config was picked up correctly, and everything worked!

Hope that helps someone else.
