### ISSUE TITLE
Running Stylelint gives a prettier error and reduces all CSS to one line

### ISSUE THREAD

**Issue by khrome83** [prettier/stylelint-prettier#19] opened 2019-04-21 01:23 UTC
**What version of `stylelint`, `prettier` and `stylelint-prettier` are you using?**

prettier - `1.17.0`
stylelint - `10.0.1`
styelint-prettier - `1.0.6`
stylelint-config-prettier - `5.1.0`

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.stylelintrc` files)**

```json
{
  "extends": ["stylelint-prettier/recommended"],
  "ignoreFiles": [
    "dist/**",
    "**/*.json",
    "**/*.ico"
  ]
}

```

**What source code are you linting?**

Original
```vue
<style scoped>
.header {
  font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
}

.cards {
  display: flex;
  flex-wrap: wrap;
}
</style>
```

**What did you expect to happen?**

Lint normally without reducing all CSS to one line.

**What actually happened?**

Output
```vue
<style scoped>
.header { font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif; } .cards
{ display: flex; flex-wrap: wrap; }
</style>
```

```shell

components/Card.vue
 19:9  ✖  Replace                                                                                                                                          prettier/prettier
          "␍⏎··font-family:·"Segoe·UI",·Tahoma,·Geneva,·Verdana,·sans-serif;␍⏎··padding:·1rem;␍⏎··display:·block;␍⏎··margin:·0.25rem;␍⏎··border:·0.                         
          25rem·solid·gainsboro;␍⏎}␍" with                                                                                                                                  
          "·font-family:·"Segoe·UI",·Tahoma,·Geneva,·Verdana,·sans-serif;·padding:⏎1rem;·display:·block;·margin:·0.25rem;·border:·0.                                        
          25rem·solid·gainsboro;·}"                                                                                                                                         

components/NewUser.vue
 41:12  ✖  Delete "⏎·"                                                                                                                                     prettier/prettier
 43:1   ✖  Replace "··padding:·1rem;⏎··margin:·0.25rem;⏎··border:·0.25rem·solid·gainsboro;⏎" with                                                          prettier/prettier
           "padding:·1rem;·margin:·0.25rem;·border:·0.25rem·solid·gainsboro;·"                                                                                              

components/UserRow.vue
 20:9  ✖  Replace                                                                                                                                          prettier/prettier
          "␍⏎··font-family:·"Segoe·UI",·Tahoma,·Geneva,·Verdana,·sans-serif;␍⏎··padding:·1rem;␍⏎··margin:·0.25rem;␍⏎··border:·0.25rem·solid·gainsboro;                      
          ␍⏎}␍" with "·font-family:·"Segoe·UI",·Tahoma,·Geneva,·Verdana,·sans-serif;·padding:⏎1rem;·margin:·0.25rem;·border:·0.25rem·solid·gainsboro;·}"                    

components/VideoPreview.vue
 31:17  ✖  Replace "⏎··width:·31.25rem;⏎··height:·23.4375;⏎··background-color:·#666;⏎" with "·width:·31.25rem;·height:·23.4375;·background-color:·#666;·"  prettier/prettier

pages/index.vue
 42:10  ✖  Replace "⏎··font-family:·"Segoe·UI",·Tahoma,·Geneva,·Verdana,·sans-serif;⏎}⏎⏎.cards·{⏎··display:·flex;⏎··flex-wrap:·wrap;⏎" with                prettier/prettier
           "·font-family:·"Segoe·UI",·Tahoma,·Geneva,·Verdana,·sans-serif;·}·.cards⏎{·display:·flex;·flex-wrap:·wrap;·"
```

**Comment by BPScott** [comment] 2019-05-07 19:44
This sounds like a duplicate of #18. I'm going to close this so we can focus the conversation in there.

**Closed by BPScott** 2019-05-07 19:44 UTC
